from cryptography.fernet import Fernet
from app.core.config import settings

# In production, ENCRYPTION_KEY should be set in environment variables
# Format: A base64-encoded 32-byte key generated by Fernet.generate_key()
# For development fallback, we generate a random key if not set.
# Note: Data encrypted with a fallback key cannot be decrypted after server restart!
def _get_cipher() -> Fernet:
    key = settings.ENCRYPTION_KEY
    if not key:
        import base64
        import os
        key = base64.urlsafe_b64encode(os.urandom(32)).decode()
    return Fernet(key.encode())

cipher_suite = _get_cipher()

def encrypt_token(plain_token: str) -> str:
    """Mã hóa Facebook/Instagram Access Token trước khi lưu vào DB"""
    if not plain_token:
        return plain_token
    encrypted = cipher_suite.encrypt(plain_token.encode())
    return encrypted.decode()

def decrypt_token(encrypted_token: str) -> str:
    """Giải mã Access Token khi cần gọi API"""
    if not encrypted_token:
        return encrypted_token
    try:
        decrypted = cipher_suite.decrypt(encrypted_token.encode())
        return decrypted.decode()
    except Exception as e:
        # For backward compatibility with unencrypted tokens during migration
        return encrypted_token
